import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/providers";
import { CartStoreProvider } from "@/store/cart-provider";
import QueryProvider from "@/components/QueryProvider";
import { AddressStoreProvider } from "@/store/address-provider";
export const metadata: Metadata = {
  title: "HiAccess",
  description: "Generated by create next app",
  icons: "/logo.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <QueryProvider>
          <CartStoreProvider>
            <AddressStoreProvider>
              <Providers>{children}</Providers>
            </AddressStoreProvider>
          </CartStoreProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
